import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html className="min-h-screen bg-sky-950" lang="en">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className="">{children}</body>
    </html>
  );
}
